// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pijxcyzspwrtcjtlhnxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpanhjeXpzcHdydGNqdGxobnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDQ3NjMsImV4cCI6MjA3MTY4MDc2M30.Hzl4HOUmZ8BGnEmTtjC1qqOY5R5OeQVncU5kuALdWmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});